/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.WelcomeController;
import Model.BangDiem;
import Model.Student;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author dell
 */
public class BangDiemModuleView extends javax.swing.JFrame {
    
    private DefaultTableModel tb ; 
    public BangDiemModuleView() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input_msv = new javax.swing.JTextField();
        input_oop = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        input_cnpm = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        input_clt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        input_ktvxl = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT TRANSCRIPT'S MODULE");

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_back.setForeground(new java.awt.Color(0, 0, 204));
        btn_back.setText("BACK");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registation"));

        jLabel3.setText("Ma_Sinh_Vien");

        jLabel4.setText("OOP");

        jLabel5.setText("CNPM");

        btn_add.setText("Add");

        btn_edit.setText("Edit");

        btn_delete.setText("Delete");

        jLabel6.setText("C++");

        jLabel7.setText("KTVXL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_ktvxl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_msv, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_oop, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_cnpm, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_clt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(input_msv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(input_oop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_cnpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_clt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(input_ktvxl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete))
                .addGap(29, 29, 29))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "OOP", "CNPM", "C++", "KTVXL", "DiemTB"
            }
        ));
        jTable1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(135, 135, 135)
                        .addComponent(btn_back)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btn_back))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
     private Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/qlth", "root","team6oop");
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
   
   // Execute The Insert Update And Delete Querys
   private void executeSQlQuery(ArrayList<BangDiem> bdList,ArrayList<Student> stuList,String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           
           // thực thi câu lệnh truy vấn
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               tb.setRowCount(0);
               Show_Users_In_JTable(bdList,stuList);
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
       }
   } 
   
    // Display Data In JTable
   public void Show_Users_In_JTable(ArrayList<BangDiem> bdList,ArrayList<Student> stuList)
   {
       tb = (DefaultTableModel) jTable1.getModel();
       Object[] row = new Object[7];
       for(int i = 0; i < bdList.size(); i++)
       {
           row[0] = bdList.get(i).getId();
           for(Student stu : stuList) {
               if(stu.getId().equals(bdList.get(i).getMsv())) {
                 row[1] = stu.getName();
           }
           }
           row[2] = bdList.get(i).getOOP();
           row[3] = bdList.get(i).getCNPM();
           row[4] = bdList.get(i).getClt();
           row[5] = bdList.get(i).getKTVXL();
           row[6] = bdList.get(i).getDTB();
           tb.addRow(row);
       }
    }
   
    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
       WelcomeView wv = new WelcomeView();
       WelcomeController wc = new WelcomeController(wv);
       dispose();
    }//GEN-LAST:event_btn_backMouseClicked
    
    public void addBangDiem(ArrayList<BangDiem> bdList,ArrayList<Student> stuList) {
        btn_add.addActionListener((e) -> {
        BangDiem bd = new BangDiem(input_msv.getText(),Double.parseDouble(input_oop.getText()),Double.parseDouble(input_cnpm.getText()),Double.parseDouble(input_clt.getText()),Double.parseDouble(input_ktvxl.getText()));
        Double dtb = tinh_dtb(Double.parseDouble(input_oop.getText()),Double.parseDouble(input_cnpm.getText()),Double.parseDouble(input_clt.getText()),Double.parseDouble(input_ktvxl.getText()));
        bd.setDTB(dtb);
        bdList.add(bd);
        String query = "INSERT INTO `bang diem`(`Id` , `Ma_Sinh_Vien`, `OOP`, `CNPM`, `C++`, `KTVXL` ,`DTB`) VALUES ('"+bd.getId()+"','"+bd.getMsv()+"','"+bd.getOOP()+"','"+bd.getCNPM()+"','"+bd.getClt()+"','"+bd.getKTVXL()+"','"+bd.getDTB()+"')";
        executeSQlQuery(bdList,stuList,query, "Inserted");
        });
    }
    
    public Double tinh_dtb(Double a,Double b,Double c,Double d) {
       Double dtb = (a+b+c+d)/4;
       return dtb;
   }
    
   public void editBangDiem(ArrayList<BangDiem> bdList,ArrayList<Student> stuList) {
       btn_edit.addActionListener((e) -> {
        for(BangDiem bd : bdList) {
            if(input_msv.getText().equals(bd.getMsv())) {
              Double oop,cnpm,clt,ktvxl ;
              oop = Double.parseDouble(input_oop.getText()) ;
              cnpm = Double.parseDouble(input_cnpm.getText());
              clt = Double.parseDouble(input_clt.getText());
              ktvxl = Double.parseDouble(input_ktvxl.getText());
              if( oop == bd.getOOP() && cnpm == bd.getCNPM() && clt == bd.getClt() && ktvxl == bd.getKTVXL()) {
                   this.resetText();
                   JOptionPane.showMessageDialog(null, "Xin vui lòng nhập dữ liệu mới để hệ thống cập nhật .");
                    return ;
              }
              bd.setOOP(oop);
              bd.setCNPM(cnpm);
              bd.setClt(clt);
              bd.setKTVXL(ktvxl); 
              Double dtb = tinh_dtb(oop,cnpm,clt,ktvxl);
              bd.setDTB(dtb);
              this.resetText();
              String query = "UPDATE `bang diem` SET `OOP`='"+bd.getOOP()+"',`CNPM`='"+bd.getCNPM()+"',`C++`='"+bd.getClt()+"',`KTVXL`='"+bd.getKTVXL()+"',`DTB`='"+bd.getDTB()+"' WHERE Ma_Sinh_Vien = '"+bd.getMsv()+"'";
              executeSQlQuery(bdList,stuList,query, "Updated");
              break;
            }
        }       
         });  
    }
    
    private void resetText() {
        input_msv.setText("");
        input_oop.setText("");
        input_cnpm.setText("");     
        input_clt.setText("");
        input_ktvxl.setText("");
    }
    public void deleteBangDiem(ArrayList<BangDiem> bdList,ArrayList<Student> stuList) {
       btn_delete.addActionListener((e) -> {
        for(BangDiem bd : bdList) {
            if(input_msv.getText().equals(bd.getMsv())) {
              bdList.remove(bd);
              BangDiem.setCount(BangDiem.getCount()-1);
              this.resetText();
              String query = "DELETE FROM `bang diem` WHERE Ma_Sinh_Vien = '"+bd.getMsv()+"'";      
              executeSQlQuery(bdList,stuList,query, "Deleted");
              break;
            }
        } 
        });
       
    }
    
    public void chonHang(ArrayList<BangDiem> bdList) {
        jTable1.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // TODO add your handling code here:
      try {
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
         // Display Slected Row In JTexteFields
        //input_id.setText(model.getValueAt(i,0).toString());
        String text = model.getValueAt(i,0).toString() ;      
        String text_msv = bdList.get(Integer.parseInt(text)-1).getMsv();
        input_msv.setText(text_msv);

        input_oop.setText(model.getValueAt(i,2).toString());

        input_cnpm.setText(model.getValueAt(i,3).toString());
        
        input_clt.setText(model.getValueAt(i,4).toString());
        
        input_ktvxl.setText(model.getValueAt(i,5).toString());
        
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
       }
        }
      });
         
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JLabel btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JTextField input_clt;
    private javax.swing.JTextField input_cnpm;
    private javax.swing.JTextField input_ktvxl;
    private javax.swing.JTextField input_msv;
    private javax.swing.JTextField input_oop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
