/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.WelcomeController;
import Model.Book;
import Model.Gvms;
import Model.Student;
import Model.Svms;
import Model.Teacher;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author dell
 */
public class BookModuleView extends javax.swing.JFrame {

    private DefaultTableModel tb1 , tb2 ;
    private int count = 0 ;
    public BookModuleView() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        input_id = new javax.swing.JTextField();
        input_name = new javax.swing.JTextField();
        input_tac_gia = new javax.swing.JTextField();
        input_gia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_add1 = new javax.swing.JButton();
        btn_edit1 = new javax.swing.JButton();
        btn_delete1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        input_ms = new javax.swing.JTextField();
        input_ma = new javax.swing.JTextField();
        input_ngay_tra = new javax.swing.JTextField();
        input_ngay_muon = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 35)); // NOI18N
        jLabel1.setText("BOOK'S MODULE");

        btn_back.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_back.setForeground(new java.awt.Color(0, 0, 204));
        btn_back.setText("BACK");
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registation"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel2.setText("Mã  :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel3.setText("Tên :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Tác Giả :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("Giá :");

        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_add.setText("Add");

        btn_edit.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_edit.setText("Edit");

        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_delete.setText("Delete");

        input_id.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        input_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_idActionPerformed(evt);
            }
        });

        input_name.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        input_name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });

        input_tac_gia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        input_tac_gia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_tac_gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_tac_giaActionPerformed(evt);
            }
        });

        input_gia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        input_gia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_gia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_giaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(input_name, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_id)
                            .addComponent(input_tac_gia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_gia))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 144, Short.MAX_VALUE)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete)
                        .addGap(2, 2, 2))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(input_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_tac_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_edit)
                    .addComponent(btn_delete))
                .addGap(44, 44, 44))
        );

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Tên", "Tác Giả", "Giá"
            }
        ));
        jTable1.setRequestFocusEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sách", jPanel2);

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Sách", "Người Mượn", "Ngày Mượn", "Ngày Trả"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(30);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Registation"));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Sách :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Ngày Mượn :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Ngày Trả :");

        btn_add1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_add1.setText("Add");

        btn_edit1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_edit1.setText("Edit");

        btn_delete1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btn_delete1.setText("Delete");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinh Viên", "Giáo Viên" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Nhập ID :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("Người Mượn :");

        input_ms.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        input_ms.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_ms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_msActionPerformed(evt);
            }
        });

        input_ma.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        input_ma.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_maActionPerformed(evt);
            }
        });

        input_ngay_tra.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        input_ngay_tra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_ngay_tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_ngay_traActionPerformed(evt);
            }
        });

        input_ngay_muon.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        input_ngay_muon.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_ngay_muon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_ngay_muonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(input_ms, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_ngay_tra, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btn_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete1)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(input_ngay_muon, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(input_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(input_ms, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(input_ngay_tra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add1)
                    .addComponent(btn_edit1)
                    .addComponent(btn_delete1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(231, Short.MAX_VALUE)
                    .addComponent(input_ngay_muon, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(172, 172, 172)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mượn Sách", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(404, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_back)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(378, 378, 378))))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
     private Connection getConnection()
   {
       Connection con;
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/qlth", "root","team6oop");
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
     
   // Execute The Insert Update And Delete Querys
   public void executeSQlQuery1(ArrayList<Book> bookList,String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           
           // thực thi câu lệnh truy vấn
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               tb1.setRowCount(0);
               HienThi_Sach(bookList);
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
       }
   }
   
   
   // excecute student
   public void executeSQlQuery2(ArrayList<Svms> svmsList,ArrayList<Book> bookList,ArrayList<Student> stuList,String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           
           // thực thi câu lệnh truy vấn
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               tb2.setRowCount(0);
               HienThi_SVms(svmsList,bookList,stuList);
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
       }
   }
   
   // excecute teacher
   public void executeSQlQuery3(ArrayList<Gvms> gvmsList,ArrayList<Book> bookList,ArrayList<Teacher> teaList,String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
           
           // thực thi câu lệnh truy vấn
           if((st.executeUpdate(query)) == 1)
           {
               // refresh jtable data
               tb2.setRowCount(0);
               HienThi_GVms(gvmsList,bookList,teaList);
               
               JOptionPane.showMessageDialog(null, "Data "+message+" Succefully");
           }else{
               JOptionPane.showMessageDialog(null, "Data Not "+message);
           }
       }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
       }
   }
   
   // Display Data In JTable
   public void HienThi_Sach(ArrayList<Book> bookList)
   {
        tb1 = (DefaultTableModel) jTable1.getModel();
       Object[] row = new Object[4];
       for(int i = 0; i < bookList.size(); i++)
       {
           row[0] = bookList.get(i).getId();
           row[1] = bookList.get(i).getName();
           row[2] = bookList.get(i).getTac_gia();
           row[3] = bookList.get(i).getGia();
           tb1.addRow(row);
       }
    }
   
   // hien thi svms 
    public void HienThi_SVms(ArrayList<Svms> svmsList,ArrayList<Book> bookList,ArrayList<Student> stuList)
   {
       tb2 = (DefaultTableModel) jTable2.getModel();
       Object[] row = new Object[4];
       for(int i = 0; i < svmsList.size(); i++)
       {
           for(Book bk : bookList) {
               if(bk.getId().equals(svmsList.get(i).getMa_sach())) {      
                 row[0] = bk.getName();
                 break ;
           }
           }
           for(Student stu : stuList) {
               if(stu.getId().equals(svmsList.get(i).getMa_sv())) {
                 row[1] = stu.getName();
                 break;
           }
           }
           row[2] = svmsList.get(i).getNgay_muon();
           row[3] = svmsList.get(i).getNgay_tra();
           tb2.addRow(row);
       }
    }
    
    // hien thi gvms
    public void HienThi_GVms(ArrayList<Gvms> gvmsList,ArrayList<Book> bookList,ArrayList<Teacher> teaList)
   {
       tb2 = (DefaultTableModel) jTable2.getModel();
       Object[] row = new Object[4];
       for(int i = 0; i < gvmsList.size(); i++)
       {
           for(Book bk : bookList) {
               if(bk.getId().equals(gvmsList.get(i).getMa_sach())) {      
                 row[0] = bk.getName();
                 break ;
           }
           }
           for(Teacher tea : teaList) {
               if(tea.getId().equals(gvmsList.get(i).getMa_gv())) {
                 row[1] = tea.getName();
                 break;
           }
           }
           row[2] = gvmsList.get(i).getNgay_muon();
           row[3] = gvmsList.get(i).getNgay_tra();
           tb2.addRow(row);
       }
    }
    
    // thao tac book
    public void addBook(ArrayList<Book> bookList) {
        btn_add.addActionListener((e) -> {
        Book bk = new Book(input_id.getText(), input_name.getText(), input_tac_gia.getText(), Integer.parseInt(input_gia.getText()));
        bookList.add(bk);
        String query = "INSERT INTO `sach`(`Ma_Sach`, `Ten`, `Tac_Gia`, `Gia` ) VALUES ('"+bk.getId()+"','"+bk.getName()+"','"+bk.getTac_gia()+"','"+bk.getGia()+"')";
        executeSQlQuery1(bookList,query, "Inserted");
        });
        
    }
    
    public void editBook(ArrayList<Book> bookList) {
        btn_edit.addActionListener((e) -> {
          for(Book bk : bookList) {
            if(input_id.getText().equals(bk.getId())) {
              if(input_name.getText().equals(bk.getName()) && input_tac_gia.getText().equals(bk.getTac_gia()) && Integer.parseInt(input_gia.getText()) == bk.getGia()) {
                 this.resetText();
                  JOptionPane.showMessageDialog(null, "Xin vui lòng nhập dữ liệu mới để hệ thống cập nhật .");
                  return ;
              }
              bk.setName(input_name.getText());
              bk.setTac_gia(input_tac_gia.getText());
              bk.setGia(Integer.parseInt(input_gia.getText()));
              this.resetText();
              String query = "UPDATE `sach` SET `Ten`='"+bk.getName()+"',`Tac_Gia`='"+bk.getTac_gia()+"',`Gia`='"+bk.getGia()+"' WHERE Ma_Sach = '"+bk.getId()+"'";
              executeSQlQuery1(bookList,query, "Updated");
              break;
            }
          }
        });         
    }  
   public void deleteBook(ArrayList<Book> bookList) {
        btn_delete.addActionListener((e) -> {
        for(Book bk : bookList) {
            if(input_id.getText().equals(bk.getId())) {
              bookList.remove(bk);
              this.resetText();
              String query = "DELETE FROM `sach` WHERE Ma_Sach = '"+bk.getId()+"'";  
              executeSQlQuery1(bookList,query, "Deleted"); 
              break;
            }
        } 
     }); 
    }
    private void resetText() {
        input_id.setText("");
        input_name.setText("");
        input_tac_gia.setText("");
        input_gia.setText("");
    }
    
   // thao tac svms
   public void addMsBook(ArrayList<Svms> svmsList,ArrayList<Gvms> gvmsList,ArrayList<Student> stuList,ArrayList<Teacher> teaList,ArrayList<Book> bookList){   
       btn_add1.addActionListener((e) -> {
          if(this.count == 0) {
        Svms svms = new Svms(input_ma.getText(), input_ms.getText(), input_ngay_muon.getText(), input_ngay_tra.getText());
        svmsList.add(svms);
        String query = "INSERT INTO `SV MUON SACH`(`Ma_Sinh_Vien`, `Ma_Sach`, `Ngay_Muon`, `Ngay_Tra` ) VALUES ('"+svms.getMa_sv()+"','"+svms.getMa_sach()+"','"+svms.getNgay_muon()+"','"+svms.getNgay_tra()+"')";
        executeSQlQuery2(svmsList,bookList,stuList,query, "Inserted");
          }
          else if (this.count == 1) {
             Gvms gvms = new Gvms(input_ma.getText(), input_ms.getText(), input_ngay_muon.getText(), input_ngay_tra.getText());
            gvmsList.add(gvms);
            String query = "INSERT INTO `GV MUON SACH`(`Ma_Giao_Vien`, `Ma_Sach`, `Ngay_Muon`, `Ngay_Tra` ) VALUES ('"+gvms.getMa_gv()+"','"+gvms.getMa_sach()+"','"+gvms.getNgay_muon()+"','"+gvms.getNgay_tra()+"')";
            executeSQlQuery3(gvmsList,bookList,teaList,query, "Inserted");
          }
       });
    }
    public void editMsBook(ArrayList<Svms> svmsList,ArrayList<Gvms> gvmsList,ArrayList<Student> stuList,ArrayList<Teacher> teaList,ArrayList<Book> bookList){   
        btn_edit1.addActionListener((e) -> {
    if(this.count == 0) {
        for(Svms svms : svmsList) {
            if(input_ma.getText().equals(svms.getMa_sv()) && input_ms.getText().equals(svms.getMa_sach())) {
                if(input_ngay_muon.getText().equals(svms.getNgay_muon()) && input_ngay_tra.getText().equals(svms.getNgay_tra())) {
                    this.resetTextMs();
                    JOptionPane.showMessageDialog(null, "Xin vui lòng nhập dữ liệu mới để hệ thống cập nhật .");
                    return ;
                }
              svms.setNgay_muon(input_ngay_muon.getText());
              svms.setNgay_tra(input_ngay_tra.getText());
              this.resetTextMs();
              String query = "UPDATE `SV MUON SACH` SET `Ngay_Muon`='"+svms.getNgay_muon()+"',`Ngay_Tra`='"+svms.getNgay_tra()+"' WHERE Ma_Sinh_Vien = '"+svms.getMa_sv()+"' AND Ma_Sach = '"+svms.getMa_sach()+"'";
              executeSQlQuery2(svmsList,bookList,stuList,query, "Updated");
              break;
            }
        }
            }
    else if(this.count == 1) {
        for(Gvms gvms : gvmsList) {
            if(input_ma.getText().equals(gvms.getMa_gv()) && input_ms.getText().equals(gvms.getMa_sach())) {
                if(input_ngay_muon.getText().equals(gvms.getNgay_muon()) && input_ngay_tra.getText().equals(gvms.getNgay_tra())) {
                    this.resetTextMs();
                    JOptionPane.showMessageDialog(null, "Xin vui lòng nhập dữ liệu mới để hệ thống cập nhật .");
                    return ;
                }
              gvms.setNgay_muon(input_ngay_muon.getText());
              gvms.setNgay_tra(input_ngay_tra.getText());
              this.resetTextMs();
              String query = "UPDATE `GV MUON SACH` SET `Ngay_Muon`='"+gvms.getNgay_muon()+"',`Ngay_Tra`='"+gvms.getNgay_tra()+"' WHERE Ma_Giao_Vien = '"+gvms.getMa_gv()+"' AND Ma_Sach = '"+gvms.getMa_sach()+"'";
              executeSQlQuery3(gvmsList,bookList,teaList,query, "Updated");
              break;
            }
        }
      }
       });
    }
    
    public void deleteMsBook(ArrayList<Svms> svmsList,ArrayList<Gvms> gvmsList,ArrayList<Student> stuList,ArrayList<Teacher> teaList,ArrayList<Book> bookList){   
        btn_delete1.addActionListener((e) -> { 
    if(this.count == 0) { 
        for(Svms svms : svmsList) {
            if(input_ma.getText().equals(svms.getMa_sv()) && input_ms.getText().equals(svms.getMa_sach())) {
              svmsList.remove(svms);
              this.resetTextMs();
              String query = "DELETE FROM `SV MUON SACH` WHERE Ma_Sach = '"+svms.getMa_sach()+"' AND Ma_Sinh_Vien = '"+svms.getMa_sv()+"'"; 
              executeSQlQuery2(svmsList,bookList,stuList,query,  "Deleted"); 
              break;
            }
        } 
    }
    else  if(this.count == 1) { 
       for(Gvms gvms : gvmsList) {
            if(input_ma.getText().equals(gvms.getMa_gv()) && input_ms.getText().equals(gvms.getMa_sach())) {
              gvmsList.remove(gvms);
              this.resetTextMs();
              String query = "DELETE FROM `GV MUON SACH` WHERE Ma_Sach = '"+gvms.getMa_sach()+"' AND Ma_Giao_Vien = '"+gvms.getMa_gv()+"'"; 
              executeSQlQuery3(gvmsList,bookList,teaList,query,  "Deleted"); 
              break;
            }
        } 
    } 
   });
 }
    
    
    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
       WelcomeView wv = new WelcomeView();
       WelcomeController wc = new WelcomeController(wv);
       dispose();
    }//GEN-LAST:event_btn_backMouseClicked
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // Get The Index Of The Slected Row
        int i = jTable1.getSelectedRow();

        TableModel model = jTable1.getModel();

        // Display Slected Row In JTexteFields
        input_id.setText(model.getValueAt(i,0).toString());

        input_name.setText(model.getValueAt(i,1).toString());

        input_tac_gia.setText(model.getValueAt(i,2).toString());

        input_gia.setText(model.getValueAt(i,3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void input_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_idActionPerformed

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void input_tac_giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_tac_giaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_tac_giaActionPerformed

    private void input_giaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_giaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_giaActionPerformed

    private void input_msActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_msActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_msActionPerformed

    private void input_maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_maActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_maActionPerformed

    private void input_ngay_traActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_ngay_traActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_ngay_traActionPerformed

    private void input_ngay_muonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_ngay_muonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_ngay_muonActionPerformed
    
    
    public void doi_bangms(ArrayList<Svms> svmsList,ArrayList<Gvms> gvmsList,ArrayList<Student> stuList,ArrayList<Teacher> teaList,ArrayList<Book> bookList){
      jComboBox1.addActionListener((e) -> {
        int index = jComboBox1.getSelectedIndex();
         if(index == 1) {
           this.count = 1;
          // reset text
          this.resetTextMs();
          // hien thi gvms
          tb2.setRowCount(0);
          this.HienThi_GVms(gvmsList, bookList, teaList); 
        } 
        else if(index == 0){
           this.count = 0 ;
          // reset text
          this.resetTextMs();
          // hien thi svms
          tb2.setRowCount(0);
          this.HienThi_SVms(svmsList, bookList, stuList);
        }
      });
    }
    
    private void resetTextMs() {
       input_ma.setText("");
       input_ms.setText("");
       input_ngay_muon.setText("");
       input_ngay_tra.setText("");
    }   
   
    
    public void chonHangMs(ArrayList<Svms> svmsList,ArrayList<Gvms> gvmsList) {
         jTable2.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // TODO add your handling code here:
         if(count == 1) {
          try {
        int i = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        
        String ma= gvmsList.get(i).getMa_gv();
        input_ma.setText(ma);

        String ms = gvmsList.get(i).getMa_sach();
        input_ms.setText(ms);

        input_ngay_muon.setText(model.getValueAt(i,2).toString());
        
        input_ngay_tra.setText(model.getValueAt(i,3).toString()); 
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
       }
        }
        else if (count == 0) {
           try {
        int j = jTable2.getSelectedRow();
        TableModel model = jTable2.getModel();
        
      
        String ma= svmsList.get(j).getMa_sv();
        input_ma.setText(ma);

        String ms = svmsList.get(j).getMa_sach();
        input_ms.setText(ms);

        input_ngay_muon.setText(model.getValueAt(j,2).toString());
        
        input_ngay_tra.setText(model.getValueAt(j,3).toString()); 
        
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
       }  
         }
        }
       });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_add1;
    private javax.swing.JLabel btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_delete1;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_edit1;
    private javax.swing.JTextField input_gia;
    private javax.swing.JTextField input_id;
    private javax.swing.JTextField input_ma;
    private javax.swing.JTextField input_ms;
    private javax.swing.JTextField input_name;
    private javax.swing.JTextField input_ngay_muon;
    private javax.swing.JTextField input_ngay_tra;
    private javax.swing.JTextField input_tac_gia;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
