/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BangDiemModuleController;
import Controller.BookModuleController;
import Controller.LoginPageController;
import Controller.StudentModuleController;
import Controller.TeacherModuleController;
import Model.BangDiem;
import Model.Student;
import Model.Book;
import Model.Teacher;

/**
 *
 * @author dell
 */
public class WelcomeView extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    
    
    public WelcomeView() {
        initComponents();
        this.setVisible(true);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bt_ts = new javax.swing.JButton();
        bt_teacher = new javax.swing.JButton();
        button_logout = new javax.swing.JLabel();
        bt_st = new javax.swing.JButton();
        bt_book = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 35)); // NOI18N
        jLabel1.setText("Menu Page");

        bt_ts.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bt_ts.setText("STUDENT TRANSCRIPT'S MODULE");

        bt_teacher.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bt_teacher.setText("TEACHER'S MODULE");
        bt_teacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_teacherActionPerformed(evt);
            }
        });

        button_logout.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        button_logout.setForeground(new java.awt.Color(255, 0, 0));
        button_logout.setText("LOGOUT");
        button_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_logoutMouseClicked(evt);
            }
        });

        bt_st.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bt_st.setText("STUDENT'S MODULE");
        bt_st.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_stActionPerformed(evt);
            }
        });

        bt_book.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        bt_book.setText("BOOK'S MODULE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288)
                        .addComponent(button_logout)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bt_st, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(bt_book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_ts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(228, 228, 228))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(button_logout)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_st, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_book, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void StudentModuleView(){
        bt_st.addActionListener((e) -> {
          Student st = new Student();
          StudentModuleView sv = new StudentModuleView();
          StudentModuleController smc = new StudentModuleController(st,sv);
          dispose();
        });
    }
     public void TeacherModuleView(){
        bt_teacher.addActionListener((e) -> {
          Teacher tt = new Teacher();
          TeacherModuleView tmv = new TeacherModuleView();
          TeacherModuleController tmc = new TeacherModuleController(tt,tmv);
          dispose();
        });
    }
    
    public void BangDiemModuleView(){
        bt_ts.addActionListener((e) -> {
        BangDiem bd = new BangDiem();
        BangDiemModuleView bmv = new  BangDiemModuleView();
        BangDiemModuleController bdm = new BangDiemModuleController(bd,bmv);
        dispose();
        });
        
    }
    
    public void BookModuleView() {
        bt_book.addActionListener((e) -> {
        Book bk = new Book();
        BookModuleView bmv = new  BookModuleView();
        BookModuleController bmc = new BookModuleController(bk,bmv);
        dispose();
        });
    }
    private void button_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_logoutMouseClicked
        // TODO add your handling code here:
        LoginPageView lpv = new LoginPageView() ;
        LoginPageController lgc = new LoginPageController(lpv) ;
        dispose();
    }//GEN-LAST:event_button_logoutMouseClicked

    private void bt_stActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_stActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_stActionPerformed

    private void bt_teacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_teacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_teacherActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_book;
    private javax.swing.JButton bt_st;
    private javax.swing.JButton bt_teacher;
    private javax.swing.JButton bt_ts;
    private javax.swing.JLabel button_logout;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
