/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BangDiemModuleController;
import Controller.BookModuleController;
import Controller.LoginPageController;
import Controller.StudentModuleController;
import Model.BangDiem;
import Model.Student;
import Model.Book;

/**
 *
 * @author dell
 */
public class WelcomeView extends javax.swing.JFrame {

    /**
     * Creates new form welcome
     */
    
    
    public WelcomeView() {
        initComponents();
        this.setVisible(true);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bt_ts = new javax.swing.JButton();
        bt_teacher = new javax.swing.JButton();
        button_logout = new javax.swing.JLabel();
        bt_st = new javax.swing.JButton();
        bt_book = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Menu Page");

        bt_ts.setText("STUDENT TRANSCRIPT'S MODULE");

        bt_teacher.setText("TEACHER'S MODULE");

        button_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_logout.setForeground(new java.awt.Color(255, 0, 0));
        button_logout.setText("LOGOUT");
        button_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_logoutMouseClicked(evt);
            }
        });

        bt_st.setText("STUDENT'S MODULE");

        bt_book.setText("BOOK'S MODULE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button_logout)
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_st, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_book, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_ts)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bt_teacher)
                                .addGap(37, 37, 37)))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(262, 262, 262))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(button_logout)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_teacher, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_st, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_ts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_book, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void StudentModuleView(){
        bt_st.addActionListener((e) -> {
          Student st = new Student();
          StudentModuleView sv = new StudentModuleView();
          StudentModuleController smc = new StudentModuleController(st,sv);
        });
    }
    
    public void BangDiemModuleView(){
        bt_ts.addActionListener((e) -> {
        BangDiem bd = new BangDiem();
        BangDiemModuleView bmv = new  BangDiemModuleView();
        BangDiemModuleController bdm = new BangDiemModuleController(bd,bmv);
        });
    }
    
    public void BookModuleView() {
        bt_book.addActionListener((e) -> {
        Book bk = new Book();
        BookModuleView bmv = new  BookModuleView();
        BookModuleController bmc = new BookModuleController(bk,bmv);
        });
    }
    private void button_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_logoutMouseClicked
        // TODO add your handling code here:
        LoginPageController lpc = new LoginPageController() ;
        LoginPageView lpv = new LoginPageView(lpc);
        dispose();
    }//GEN-LAST:event_button_logoutMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_book;
    private javax.swing.JButton bt_st;
    private javax.swing.JButton bt_teacher;
    private javax.swing.JButton bt_ts;
    private javax.swing.JLabel button_logout;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
